### ISSUE TITLE
Reinstalling Factory Firmware - not working

### ISSUE THREAD

**Issue by heemdijk** [robertzak133/BTC-7-8E-HP5-Firmware-Images#1]
My camera's date-time recording resets after a few hours. Then the factory time is entered. Suspect this is a hardware issue. To restore the original software to the factory firmware, I put "Baseline" on SD card.
SD in camera
Press "Mode" button
Select "CAMERA SETUP"
Select "FW UPGRADE"

Only I can't select Yes here? I do see WWL7EHS_221210A as version.

I love the new version, but my camera needs to register a correct date format. This problem was also for this great version on this camera. Want to return the camera with original software

**Comment by robertzak133** [comment]
There was a bug in the firmware labeled "WWL7EH5_221210A" (for the 7E-HP5) and "WWL8EH5_221210A" (for the 8E-HP5) which prevents new firmware from being loaded.  This was caused by a new data structure in the menu system which I did not realize had to be terminated by a null entry.  Firmware versions "WWL7EH5_230104A" (for the 7E-HP5) and "WWL8E5H_230104A" (for the 8E-HP5) fix this problem.  Unfortunately, I do not know of a workaround for the earlier bug.  If you downloaded the buggy version, and now would like to load new firmware, please let me know in comments/issues below. I have a possible plan.

**Comment by heemdijk** [comment]
This version alow me to instal WWL7EH5_230104A

My problem on the cammera is in a battery that is soldered to the circuit board and that is apparently empty / does not charge. As a result, the real-time clock does not work and thus forgets to keep track of the time after it has been set. Whenever the camera goes into deep sleep, time gets lost and goes back to factory time.
I want to return this camera tomorrow, I will immediately receive a new one. 

I can wait a while to fix this issue correctly? your plan. Let me know

But from what I've seen, the version on the camera works great, so why would you want to go back ;-) ?

**Comment by robertzak133** [comment]
The only way I know of getting your camera with the buggy firmware back to factory firmware is in the lab.  I am worried that Browning will not honor the warranty for trail camera whose firmware has been modified (though I don't know this for sure, this being the first case).  You are welcome to try -- it may work!  If it doesn't, or you don't want to risk it, we may be able to work something out, but I'd rather do directly over email.  If you are interested, leave a comment on the blog post at: https://winterberrywildlife.ouroneacrefarm.com/2022/12/19/new-optional-features-for-browning-hp5-trail-cameras/
